package io.github.gaming32.mckt.world

import io.github.gaming32.mckt.BLOCK_MATERIALS

@Suppress("unused")
object Materials {
    private fun getMaterial(name: String) =
        BLOCK_MATERIALS[name] ?: throw Error("Standard material $name not found")

    val AIR = getMaterial("air")
    val STRUCTURE_VOID = getMaterial("structure_void")
    val PORTAL = getMaterial("portal")
    val CARPET = getMaterial("carpet")
    val PLANT = getMaterial("plant")
    val UNDERWATER_PLANT = getMaterial("underwater_plant")
    val REPLACEABLE_PLANT = getMaterial("replaceable_plant")
    val NETHER_SHOOTS = getMaterial("nether_shoots")
    val REPLACEABLE_UNDERWATER_PLANT = getMaterial("replaceable_underwater_plant")
    val WATER = getMaterial("water")
    val BUBBLE_COLUMN = getMaterial("bubble_column")
    val LAVA = getMaterial("lava")
    val SNOW_LAYER = getMaterial("snow_layer")
    val FIRE = getMaterial("fire")
    val DECORATION = getMaterial("decoration")
    val COBWEB = getMaterial("cobweb")
    val SCULK = getMaterial("sculk")
    val REDSTONE_LAMP = getMaterial("redstone_lamp")
    val ORGANIC_PRODUCT = getMaterial("organic_product")
    val SOIL = getMaterial("soil")
    val SOLID_ORGANIC = getMaterial("solid_organic")
    val DENSE_ICE = getMaterial("dense_ice")
    val AGGREGATE = getMaterial("aggregate")
    val SPONGE = getMaterial("sponge")
    val SHULKER_BOX = getMaterial("shulker_box")
    val WOOD = getMaterial("wood")
    val NETHER_WOOD = getMaterial("nether_wood")
    val BAMBOO_SAPLING = getMaterial("bamboo_sapling")
    val BAMBOO = getMaterial("bamboo")
    val WOOL = getMaterial("wool")
    val TNT = getMaterial("tnt")
    val LEAVES = getMaterial("leaves")
    val GLASS = getMaterial("glass")
    val ICE = getMaterial("ice")
    val CACTUS = getMaterial("cactus")
    val STONE = getMaterial("stone")
    val METAL = getMaterial("metal")
    val SNOW_BLOCK = getMaterial("snow_block")
    val REPAIR_STATION = getMaterial("repair_station")
    val BARRIER = getMaterial("barrier")
    val PISTON = getMaterial("piston")
    val MOSS_BLOCK = getMaterial("moss_block")
    val GOURD = getMaterial("gourd")
    val EGG = getMaterial("egg")
    val CAKE = getMaterial("cake")
    val AMETHYST = getMaterial("amethyst")
    val POWDER_SNOW = getMaterial("powder_snow")
    val FROGSPAWN = getMaterial("frogspawn")
    val FROGLIGHT = getMaterial("froglight")
}
