viewDistance = 10
simulationDistance = 10
maxPlayers = 20
seed = null
motd = text("My mckt server")
defaultWorldGenerator = WorldGenerator.NORMAL
networkCompressionThreshold = 256
autosavePeriod = 5 * 60 * 20
enableVanillaClientSpoofAlerts = true
enableChatPreview = false
